[theme]
base = "dark"  # Ativa o tema escuro
primaryColor = "#130D3C"  # Cor principal para botões e links
backgroundColor = "#130D3C"  # Cor de fundo da aplicação
secondaryBackgroundColor = "#130D3C"  # Cor de fundo da barra lateral
textColor = "#FFFFFF"  # Cor do texto principal
font = "sans serif"  # Opções: "sans serif", "serif", "monospace"
